import type { NextPage } from "next";
import Head from "next/head";

const Besic: NextPage = () => {
  return (
    <div>
      <Head>
        <title>BESI-C | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Behavioral and Environmental Sensing and Intervention for Cancer
          (BESI-C)
        </h1>
        <h2>Currently funded by: The National Institute of Nursing Research</h2>
        <p>
          <a
            href="https://reporter.nih.gov/search/Lp98QMWfW0yLnFeijLmJhA/project-details/10096693"
            target="_black"
            rel="noreferrer"
          >
            BESI-C is an NIH funded project
          </a>{" "}
          that deploys a novel remote health monitoring system to better
          understand the experience of cancer pain in the home context.
          Heterogenous physiological, contextual, and behavioral sensing data
          are collected from wearable and environmental sensors to
          comprehensively understand the experience of cancer pain from the
          perspective of both patients and family caregivers and inform future,
          tailored interventions.{" "}
          <a href="https://besic.org" target="_blank" rel="noreferrer">
            Learn more about BESI-C and our study team.
          </a>
        </p>
        <h2>Publications:</h2>
        <p>
          LeBaron, V., Alam, R., Bennett, R., Blackhall, L., Gordon, K., Hayes,
          J., Homdee, N., Jones, R., Lichti, K., Martinez, Y., Mohammadi, S.,
          Ogunjirin, E., Patel, N., & Lach, J. (2022).{" "}
          <a
            href="https://cancer.jmir.org/2022/3/e36879"
            target="_blank"
            rel="noreferrer"
          >
            Deploying the Behavioral and Environmental Sensing and Intervention
            for Cancer (BESI-C)smart health system to support patients and
            family caregivers in managing pain:Feasibility and acceptability
            study.
          </a>{" "}
          Journal of Internet Medical Research (JMIR) Cancer, 8(3); e36879
        </p>
      </main>
    </div>
  );
};

export default Besic;
