import type { NextPage } from "next";
import Head from "next/head";

const Commsense: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CommSense | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>CommSense</h1>
        <h2>
          Currently funded by: The University of Virginia Engineering in
          Medicine Seed Pilot Program
        </h2>
        <p>
          This is a feasibility and acceptability pilot study to develop a novel
          software and associated algorithms (CommSense) that can: 1) be
          deployed on mobile devices, such as smart watches; 2) reliably capture
          patient-clinician interactions in a clinical setting; 3) process these
          communications to extract key markers of communication
          effectiveness/performance; and 4) ultimately provide real-time
          feedback to end-users to improve communication and patient health
          outcomes.
        </p>
        <h2>Publications:</h2>
        <p>
          <a
            href="https://www.researchprotocols.org/2022/5/e37975"
            target="_blank"
            rel="noreferrer"
          >
            Exploring the Use of Wearable Sensors and Natural Language
            Processing Technology to Improve Patient-Clinician Communication:
            Protocol for a Feasibility Study
          </a>
        </p>
      </main>
    </div>
  );
};

export default Commsense;
