import type { NextPage } from "next";
import Head from "next/head";
import Project from "../../components/Project";

const Projects: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Projects | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Projects</h1>
        <div className="projectGrid">
          <Project href="/projects/besic" src="./favicon.ico" alt="BESI-C">
            BESI-C
          </Project>
          <Project
            href="/projects/commsense"
            src="./favicon.ico"
            alt="CommSense"
          >
            CommSense
          </Project>
          <Project
            href="/projects/napcare"
            src="./favicon.ico"
            alt="NAPCare / UVA Global Collaboration"
          >
            NAPCare / UVA Global Collaboration
          </Project>
        </div>
      </main>
    </div>
  );
};

export default Projects;
