import type { NextPage } from "next";
import Head from "next/head";

const Napcare: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NAPCare / UVA Global Collaboration | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>NAPCare / UVA Global Collaboration</h1>
        <h2>
          Recently funded by: Fogarty International Center; National Institutes
          of Health
        </h2>
        <p>
          This NIH supported global collaboration, designed to strengthen
          research capacity in low and middle-income countries, involves
          clinical and research partners in Nepal (the{" "}
          <a href="https://napcare.org.np/" target="_blank" rel="noreferrer">
            Nepalese Association of Palliative Care, NAPCare
          </a>
          ) and the United States (University of Virginia{" "}
          <a
            href="https://www.nursing.virginia.edu/"
            target="_blank"
            rel="noreferrer"
          >
            School of Nursing
          </a>{" "}
          and{" "}
          <a
            href="https://globalhealth.virginia.edu/"
            target="_blank"
            rel="noreferrer"
          >
            Center for Global Health Equity
          </a>
          ). Through this collaboration, our team developed and pilot tested a
          mobile application to digitize contextual and culturally congruent
          pain management guidelines to support healthcare providers within
          Nepal. We also created a{" "}
          <a href="https://lmicresearch.org/" target="_blank" rel="noreferrer">
            Virtual Library
          </a>{" "}
          of resources to support clinicians conducting research in
          resource-constrained environments - check it out!
        </p>
        <h2>Publications:</h2>
        <p>
          <a
            href="https://bmcpalliatcare.biomedcentral.com/articles/10.1186/s12904-021-00824-0"
            target="_blank"
            rel="noreferrer"
          >
            A Survey of Cancer Care Institutions in Nepal to Inform Design of a
            Pain Management Mobile Application.
          </a>
        </p>
        <p>
          <a
            href="https://pubmed.ncbi.nlm.nih.gov/35965597/"
            target="_blank"
            rel="noreferrer"
          >
            A Global Collaboration to Develop and Pilot Test a Mobile
            Application to Improve Cancer Pain Management in Nepal.
          </a>
        </p>
        <p>
          Building a ‘Virtual Library’: Continuing a global collaboration to
          build research capacity in Nepal and other low- and middle-income
          countries. (In press; link coming soon)
        </p>
      </main>
    </div>
  );
};

export default Napcare;
