import type { NextPage } from 'next'
import Head from 'next/head'
import ContactForm from '../components/ContactForm'
import styles from '../styles/contact_us.module.css'

const ContactUs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contact Us | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Contact Us</h1>
        <p className={styles.center}>Thank you for your interest in TECC. If you would like to contact us, submit this form, or email tecc.besic@gmail.com and a member of our team will be with you shortly.</p>
        <ContactForm />
      </main>
    </div>
  )
}

export default ContactUs
