import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>What is TECC?</h1>
        <p>
          <b>T</b>echnology <b>E</b>nhanced <b>C</b>ancer <b>C</b>are
        </p>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, consectetur voluptatem. Ullam temporibus consequuntur quos tempore iure earum, provident animi deserunt fugit recusandae totam suscipit sapiente veniam laborum aliquam architecto.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic reiciendis culpa officiis possimus nobis sed! Similique ratione ullam debitis, iste consequatur omnis praesentium pariatur. Omnis laudantium nisi exercitationem reprehenderit.
        </p>
      </main>
    </div>
  )
}

export default Home
