import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>About the Technology Enhanced Compassionate Care (TECC) Lab</h1>
        <h2>Our Mission:</h2>
        <p>
          To conduct innovative, interdisciplinary research that leverages
          technology to alleviate suffering and enhance equitable access to
          quality care – for patients, family caregivers, and healthcare
          providers – in both domestic and international settings. Current focal
          areas of the TECC lab include improving patient-clinician
          communication and optimizing safe and effective pain management for
          patients with advanced-stage cancer.
        </p>
        <h2>Lead Faculty:</h2>
        <img
          className="facultyImg"
          src="/virginia.jpg"
          alt="Virginia Lebaron"
        ></img>
        <h3>Virginia LeBaron</h3>
        <p>
          The TECC lab is directed by{" "}
          <a
            href="https://www.nursing.virginia.edu/people/vtl6k/"
            target="_blank"
            rel="noreferrer"
          >
            Virginia LeBaron
          </a>
          , Associate Professor of Nursing and the Kluge-Schakat Associate
          Professor of Compassionate Care. Dr. LeBaron’s clinical background in
          oncology and palliative care is the catalyst for her passion to
          improve the lives of patients with serious illness and those who care
          for them.
        </p>
      </main>
    </div>
  );
};

export default Home;
