import type { NextPage } from 'next'
import Head from 'next/head'

const Opportunities: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Opportunities | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Opportunities</h1>
        <p>There are no work opportunities at this time.</p>
        <p>Contact Us with the link at the footer of this page if you have any questions.</p>
      </main>
    </div>
  )
}

export default Opportunities
