import type { NextPage } from 'next'
import Head from 'next/head'
import Project from '../components/Project'

const Projects: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Projects | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Projects</h1>
        <p>Coming soon...</p>
        <div className='projectGrid'>
          <Project href='https://tecclab.org' src='./favicon.ico' alt='TECC' title='TECC'>
            Technology Enhanced Cancer Care
          </Project>
          <Project href='https://tecclab.org' src='./favicon.ico' alt='TECC' title='TECC'>
            Technology Enhanced Cancer Care
          </Project>
          <Project href='https://tecclab.org' src='./favicon.ico' alt='TECC' title='TECC'>
            Technology Enhanced Cancer Care
          </Project>
          <Project href='https://tecclab.org' src='./favicon.ico' alt='TECC' title='TECC'>
            Technology Enhanced Cancer Care
          </Project>
        </div>
      </main>
    </div>
  )
}

export default Projects
