import type { NextPage } from 'next'
import Head from 'next/head'

const Publications: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Publications | TECC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Publications</h1>
        <div>
          <a href="https://www.researchprotocols.org/2019/12/e16178"><b>Leveraging Smart Health Technology to Empower Patients and Family Caregivers in Managing Cancer Pain: Protocol for a Feasibility Study</b></a>
		      <p>LeBaron V, Hayes J, Gordon K, Alam R, Homdee N, Martinez Y, Ogunjirin E, Thomas T, Jones R, Blackhall L, Lach J. Leveraging Smart Health Technology to Empower Patients and Family Caregivers in Managing Cancer Pain: Protocol for a Feasibility Study.  JMIR Res Protoc 2019;8(12):e16178. DOI: 10.2196/16178. PMID: 31815679</p>

		      <a href="https://formative.jmir.org/2020/8/e20836/"><b>Understanding the Experience of Cancer Pain From the Perspective of Patients and Family Caregivers to Inform Design of an In-Home Smart Health System: Multimethod Approach</b></a>
		      <p>LeBaron, V., Bennett, R., Blackhall, L., Alam, R., Gordon, K., Hayes, J., Homdee, N., Martinez, Y, Ogunjirin, E., Jones, R., Thomas, T. &amp; Lach, J. (2020). Understanding the experience of cancer pain management at home from the perspective of patients and family caregivers to inform design of an in-home smart health sensing system. JMIR (Journal of Medical Internet Research) Formative Research, 4(8):e20836. PMID: 32712581</p>

		      <a href="http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&;arnumber=8877908&isnumber=8877893"><b>Agitation Monitoring and Prevention System for Dementia Caregiver Empowerment</b></a>
		      <p>N. Homdee, R. Alam, J.A. Hayes, T. Hamid, J. Park, S. Wolfe, H. Goins, N. Fyffe, T. Newbold, T. Smith-Jackson, A. Bankole, M.S. Anderson, J. Lach, &quot;Agitation Monitoring and Prevention System for Dementia Caregiver Empowerment,&quot; in Computer, vol. 52, no. 11, pp. 30-39, Nov. 2019doi: 10.1109/MC.2019.2933192</p>

		      <a href="https://www.researchprotocols.org/2019/12/e16178"><b>Leveraging Smart Health Technology to Empower Patients and Family Caregivers in Managing Cancer Pain: Protocol for a Feasibility Study</b></a>
		      <p>LeBaron V, Hayes J, Gordon K, Alam R, Homdee N, Martinez Y, Ogunjirin E, Thomas T, Jones R, Blackhall L, Lach J. Leveraging Smart Health Technology to Empower Patients and Family Caregivers in Managing Cancer Pain: Protocol for a Feasibility Study.  JMIR Res Protoc 2019;8(12):e16178. DOI: 10.2196/16178. PMID: 31815679</p>

		      <a href="https://formative.jmir.org/2020/8/e20836/"><b>Understanding the Experience of Cancer Pain From the Perspective of Patients and Family Caregivers to Inform Design of an In-Home Smart Health System: Multimethod Approach</b></a>
		      <p>LeBaron, V., Bennett, R., Blackhall, L., Alam, R., Gordon, K., Hayes, J., Homdee, N., Martinez, Y, Ogunjirin, E., Jones, R., Thomas, T. &amp; Lach, J. (2020). Understanding the experience of cancer pain management at home from the perspective of patients and family caregivers to inform design of an in-home smart health sensing system. JMIR (Journal of Medical Internet Research) Formative Research, 4(8):e20836. PMID: 32712581</p>

          <a href="http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8877908&isnumber=8877893"><b>Agitation Monitoring and Prevention System for Dementia Caregiver Empowerment</b></a>
          <p>N. Homdee, R. Alam, J.A. Hayes, T. Hamid, J. Park, S. Wolfe, H. Goins, N. Fyffe, T. Newbold, T. Smith-Jackson, A. Bankole, M.S. Anderson, J. Lach, &quot;Agitation Monitoring and Prevention System for Dementia Caregiver Empowerment,&quot; in Computer, vol. 52, no. 11, pp. 30-39, Nov. 2019doi: 10.1109/MC.2019.2933192</p>
        </div>

      </main>
    </div>
  )
}

export default Publications
